// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: gameapi.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Cmd    string `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
}

func (x *CmdReq) Reset() {
	*x = CmdReq{}
	mi := &file_gameapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdReq) ProtoMessage() {}

func (x *CmdReq) ProtoReflect() protoreflect.Message {
	mi := &file_gameapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdReq.ProtoReflect.Descriptor instead.
func (*CmdReq) Descriptor() ([]byte, []int) {
	return file_gameapi_proto_rawDescGZIP(), []int{0}
}

func (x *CmdReq) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *CmdReq) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type BindReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server   string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Player   string `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	Authcode string `protobuf:"bytes,3,opt,name=authcode,proto3" json:"authcode,omitempty"`
}

func (x *BindReq) Reset() {
	*x = BindReq{}
	mi := &file_gameapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindReq) ProtoMessage() {}

func (x *BindReq) ProtoReflect() protoreflect.Message {
	mi := &file_gameapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindReq.ProtoReflect.Descriptor instead.
func (*BindReq) Descriptor() ([]byte, []int) {
	return file_gameapi_proto_rawDescGZIP(), []int{1}
}

func (x *BindReq) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *BindReq) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *BindReq) GetAuthcode() string {
	if x != nil {
		return x.Authcode
	}
	return ""
}

type SrvAndFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server   string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Filepath string `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
}

func (x *SrvAndFile) Reset() {
	*x = SrvAndFile{}
	mi := &file_gameapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SrvAndFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrvAndFile) ProtoMessage() {}

func (x *SrvAndFile) ProtoReflect() protoreflect.Message {
	mi := &file_gameapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrvAndFile.ProtoReflect.Descriptor instead.
func (*SrvAndFile) Descriptor() ([]byte, []int) {
	return file_gameapi_proto_rawDescGZIP(), []int{2}
}

func (x *SrvAndFile) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *SrvAndFile) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

type String struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *String) Reset() {
	*x = String{}
	mi := &file_gameapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_gameapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_gameapi_proto_rawDescGZIP(), []int{3}
}

func (x *String) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ByteSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ByteSlice) Reset() {
	*x = ByteSlice{}
	mi := &file_gameapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByteSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteSlice) ProtoMessage() {}

func (x *ByteSlice) ProtoReflect() protoreflect.Message {
	mi := &file_gameapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteSlice.ProtoReflect.Descriptor instead.
func (*ByteSlice) Descriptor() ([]byte, []int) {
	return file_gameapi_proto_rawDescGZIP(), []int{4}
}

func (x *ByteSlice) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_gameapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_gameapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_gameapi_proto_rawDescGZIP(), []int{5}
}

var File_gameapi_proto protoreflect.FileDescriptor

var file_gameapi_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x50, 0x49, 0x22, 0x32, 0x0a, 0x06, 0x43, 0x6d, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x22, 0x55, 0x0a, 0x07,
	0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x40, 0x0a, 0x0a, 0x53, 0x72, 0x76, 0x41, 0x6e, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x70, 0x61, 0x74, 0x68, 0x22, 0x1c, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x1f, 0x0a, 0x09, 0x42, 0x79, 0x74, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xc9, 0x01,
	0x0a, 0x07, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x50, 0x49, 0x12, 0x2e, 0x0a, 0x0b, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x0f, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x41,
	0x50, 0x49, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x0e, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x41, 0x50, 0x49, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2b, 0x0a, 0x07, 0x53, 0x65, 0x6e,
	0x64, 0x43, 0x6d, 0x64, 0x12, 0x0f, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x50, 0x49, 0x2e, 0x43,
	0x6d, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x50, 0x49, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x2c, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x42, 0x69,
	0x6e, 0x64, 0x12, 0x10, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x50, 0x49, 0x2e, 0x42, 0x69, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x50, 0x49, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x33, 0x0a, 0x08, 0x4c, 0x6f, 0x61, 0x64, 0x4a, 0x53, 0x4f, 0x4e,
	0x12, 0x13, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x50, 0x49, 0x2e, 0x53, 0x72, 0x76, 0x41, 0x6e,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x12, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x50, 0x49, 0x2e,
	0x42, 0x79, 0x74, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x72,
	0x70, 0x63, 0x2f, 0x3b, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gameapi_proto_rawDescOnce sync.Once
	file_gameapi_proto_rawDescData = file_gameapi_proto_rawDesc
)

func file_gameapi_proto_rawDescGZIP() []byte {
	file_gameapi_proto_rawDescOnce.Do(func() {
		file_gameapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_gameapi_proto_rawDescData)
	})
	return file_gameapi_proto_rawDescData
}

var file_gameapi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gameapi_proto_goTypes = []any{
	(*CmdReq)(nil),     // 0: GameAPI.CmdReq
	(*BindReq)(nil),    // 1: GameAPI.BindReq
	(*SrvAndFile)(nil), // 2: GameAPI.SrvAndFile
	(*String)(nil),     // 3: GameAPI.String
	(*ByteSlice)(nil),  // 4: GameAPI.ByteSlice
	(*Empty)(nil),      // 5: GameAPI.Empty
}
var file_gameapi_proto_depIdxs = []int32{
	3, // 0: GameAPI.GameAPI.WorldBackup:input_type -> GameAPI.String
	0, // 1: GameAPI.GameAPI.SendCmd:input_type -> GameAPI.CmdReq
	1, // 2: GameAPI.GameAPI.GameBind:input_type -> GameAPI.BindReq
	2, // 3: GameAPI.GameAPI.LoadJSON:input_type -> GameAPI.SrvAndFile
	5, // 4: GameAPI.GameAPI.WorldBackup:output_type -> GameAPI.Empty
	3, // 5: GameAPI.GameAPI.SendCmd:output_type -> GameAPI.String
	5, // 6: GameAPI.GameAPI.GameBind:output_type -> GameAPI.Empty
	4, // 7: GameAPI.GameAPI.LoadJSON:output_type -> GameAPI.ByteSlice
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gameapi_proto_init() }
func file_gameapi_proto_init() {
	if File_gameapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gameapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gameapi_proto_goTypes,
		DependencyIndexes: file_gameapi_proto_depIdxs,
		MessageInfos:      file_gameapi_proto_msgTypes,
	}.Build()
	File_gameapi_proto = out.File
	file_gameapi_proto_rawDesc = nil
	file_gameapi_proto_goTypes = nil
	file_gameapi_proto_depIdxs = nil
}
