// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: misc.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Misc_GetGeoByIP_FullMethodName = "/misc.Misc/GetGeoByIP"
)

// MiscClient is the client API for Misc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MiscClient interface {
	GetGeoByIP(ctx context.Context, in *String, opts ...grpc.CallOption) (*Location, error)
}

type miscClient struct {
	cc grpc.ClientConnInterface
}

func NewMiscClient(cc grpc.ClientConnInterface) MiscClient {
	return &miscClient{cc}
}

func (c *miscClient) GetGeoByIP(ctx context.Context, in *String, opts ...grpc.CallOption) (*Location, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Location)
	err := c.cc.Invoke(ctx, Misc_GetGeoByIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiscServer is the server API for Misc service.
// All implementations must embed UnimplementedMiscServer
// for forward compatibility.
type MiscServer interface {
	GetGeoByIP(context.Context, *String) (*Location, error)
	mustEmbedUnimplementedMiscServer()
}

// UnimplementedMiscServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiscServer struct{}

func (UnimplementedMiscServer) GetGeoByIP(context.Context, *String) (*Location, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeoByIP not implemented")
}
func (UnimplementedMiscServer) mustEmbedUnimplementedMiscServer() {}
func (UnimplementedMiscServer) testEmbeddedByValue()              {}

// UnsafeMiscServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiscServer will
// result in compilation errors.
type UnsafeMiscServer interface {
	mustEmbedUnimplementedMiscServer()
}

func RegisterMiscServer(s grpc.ServiceRegistrar, srv MiscServer) {
	// If the following call pancis, it indicates UnimplementedMiscServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Misc_ServiceDesc, srv)
}

func _Misc_GetGeoByIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiscServer).GetGeoByIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Misc_GetGeoByIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiscServer).GetGeoByIP(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

// Misc_ServiceDesc is the grpc.ServiceDesc for Misc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Misc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "misc.Misc",
	HandlerType: (*MiscServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGeoByIP",
			Handler:    _Misc_GetGeoByIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "misc.proto",
}
